spring:
  application:
    name: Festival-Tickets-Service
  datasource:
    url: jdbc:h2:mem:tickets
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db.migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      artists-service:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        sliding-window-size: 2
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3

    circuit-breaker-aspect-order: 1
  retry:
    retry-aspect-order: 2
    instances:
      artists-service:
        max-attempts: 10
        wait-duration:
          nanos: 5000

